export const SEARCH_FOCUSED = 'header/search_focused'
export const SEARCH_BLURED = 'header/search_blured'
export const GET_SEARCH_INFO_LIST = 'header/search_info_init'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'
export const CHANGE_PAGE = 'header/change_page'